# Generated by Django 5.0 on 2023-12-26 01:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat_history',
            name='items',
        ),
        migrations.AddField(
            model_name='chat_history',
            name='answer_list',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='chat_history',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='chat_history',
            name='question_list',
            field=models.TextField(blank=True, default=''),
        ),
    ]
