# Generated by Django 5.0 on 2024-01-12 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_chat_history_answer_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_history',
            name='chat_history_title',
            field=models.TextField(blank=True, default='テストセッション'),
        ),
    ]
